webtalk_init -webtalk_dir D:/My Documents/University/Fourth Year - 2021/EEE4120F - HPES/YODA - VADER/Code/VADER/VADER.sim/sim_3/behav/xsim/xsim.dir/passwordGenTest_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun 16 00:39:34 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f9e0bcfb-9b27-45fb-a197-95b1490ca787" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8aec8eb84b0c4edcb277888147d25c02" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "38" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "175850 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8552_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2266945379 -regid "" -xml D:/My Documents/University/Fourth Year - 2021/EEE4120F - HPES/YODA - VADER/Code/VADER/VADER.sim/sim_3/behav/xsim/xsim.dir/passwordGenTest_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/My Documents/University/Fourth Year - 2021/EEE4120F - HPES/YODA - VADER/Code/VADER/VADER.sim/sim_3/behav/xsim/xsim.dir/passwordGenTest_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/My Documents/University/Fourth Year - 2021/EEE4120F - HPES/YODA - VADER/Code/VADER/VADER.sim/sim_3/behav/xsim/xsim.dir/passwordGenTest_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
